name: Build & Release Flash Tool

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: windows-latest

    steps:
      # =========================
      # CHECKOUT
      # =========================
      - name: Checkout
        uses: actions/checkout@v4

      # =========================
      # PYTHON
      # =========================
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # =========================
      # INSTALL DEPENDENCIES
      # =========================
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller tqdm

      # =========================
      # BUILD GUI (OPTIMIZED)
      # =========================
      - name: Build GUI
        run: |
          pyinstaller wizard.py ^
            --noconfirm ^
            --windowed ^
            --onedir ^
            --name USBFlashToolPro ^
            --icon=icon.ico
            --add-binary "rust-flash.exe;." ^
            --clean ^
            --strip ^
            --noupx ^
            --exclude-module tkinter.test ^
            --exclude-module unittest ^
            --exclude-module test

      # =========================
      # BUILD CLI (OPTIMIZED)
      # =========================
      - name: Build CLI
        run: |
          pyinstaller flasher.py ^
          --noconfirm ^
          --onedir ^
          --name usb-flasher-cli ^
          --icon=icon.ico ^
          --add-binary "rust-flash.exe;." ^
          --clean ^
          --strip ^
          --noupx

      # =========================
      # INSTALL NSIS
      # =========================
      - name: Install NSIS
        run: choco install nsis -y

      # =========================
      # BUILD INSTALLER
      # =========================
      - name: Build Installer
        run: |
          makensis installer.nsi

      # =========================
      # UPLOAD RELEASE
      # =========================
      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/USBFlashToolPro.exe
            dist/usb-flasher-cli.exe
            USBFlashToolPro-Setup.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
