name: Build Flash Tool

on:

  push:

    tags:

      - "v*"

jobs:

  build-windows:

    runs-on: windows-latest

    steps:

      - name: Checkout code

        uses: actions/checkout@v4

      - name: Setup Python

        uses: actions/setup-python@v5

        with:

          python-version: "3.10"

      - name: Install dependencies

        run: |

          python -m pip install --upgrade pip

          pip install pyinstaller tqdm

      # =========================

      # BUILD EXE

      # =========================

      - name: Build EXE

        run: |

          pyinstaller --noconfirm --onefile wizard.py --name USB-Flasher-Pro

      # =========================

      # CREATE RELEASE

      # =========================

      - name: Upload Release Asset

        uses: softprops/action-gh-release@v2

        with:

          files: dist/*

        env:

          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
